// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REMIwebApi.Datos;

#nullable disable

namespace REMIwebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REMIwebApi.Models.categoria", b =>
                {
                    b.Property<string>("Id_categoria")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("nombreCat")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id_categoria")
                        .HasName("PK__categori__4A033A93BC4D705C");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("REMIwebApi.Models.cliente", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id_cliente")
                        .HasName("PK__cliente__FCE039921AECE439");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("REMIwebApi.Models.metodo_de_pago", b =>
                {
                    b.Property<string>("Id_metodo")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Desc_metodo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_metodo")
                        .HasName("PK__metodo_d__AB62E2F2894D648B");

                    b.ToTable("metodo_de_pago");
                });

            modelBuilder.Entity("REMIwebApi.Models.movimientos_stock", b =>
                {
                    b.Property<int>("Id_movimiento")
                        .HasColumnType("int");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id_movimiento")
                        .HasName("PK__movimien__7B67F72A8EA7C94E");

                    b.HasIndex("Stock");

                    b.ToTable("movimientos_stock");
                });

            modelBuilder.Entity("REMIwebApi.Models.persona", b =>
                {
                    b.Property<int>("Id_Persona")
                        .HasColumnType("int");

                    b.Property<byte[]>("Contrasena")
                        .HasMaxLength(130)
                        .HasColumnType("varbinary(130)");

                    b.Property<string>("Correo")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<long?>("TelefonoCel")
                        .HasColumnType("bigint");

                    b.Property<string>("primerApellido")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("primerNombre")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("segundoApellido")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("segundoNombre")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("tipoDoc")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id_Persona")
                        .HasName("PK__persona__C95634AFE6B01855");

                    b.HasIndex("tipoDoc");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("REMIwebApi.Models.producto", b =>
                {
                    b.Property<string>("cod_Producto")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Subcategoria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("marcaProducto")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<double?>("precioDocena")
                        .HasColumnType("float");

                    b.HasKey("cod_Producto")
                        .HasName("PK__producto__C6B2843F231FCCB1");

                    b.HasIndex("Proveedor");

                    b.HasIndex("Subcategoria");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("REMIwebApi.Models.proveedore", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"));

                    b.Property<string>("correoProveedor")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("direccionProveedor")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("nombreProveedor")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("telefonoProveedor")
                        .HasColumnType("int");

                    b.HasKey("Id_Proveedor")
                        .HasName("PK__proveedo__477B858ED1A07C53");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_pago", b =>
                {
                    b.Property<int>("Id_recibo")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<int?>("Id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("Persona")
                        .HasColumnType("int");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.Property<string>("nombreNegocio")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id_recibo")
                        .HasName("PK__recibo_p__64A18CFCAA026CAC");

                    b.HasIndex("Id_cliente");

                    b.HasIndex("Persona");

                    b.ToTable("recibo_pago");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_pago_has_metodo", b =>
                {
                    b.Property<int>("recibo_pago_Id_recibo")
                        .HasColumnType("int");

                    b.Property<int>("recibo_pago_Persona")
                        .HasColumnType("int");

                    b.Property<string>("metodo_de_pago_Id_metodo")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("recibo_pago_Id_recibo", "recibo_pago_Persona", "metodo_de_pago_Id_metodo")
                        .HasName("PK__recibo_p__10972F1BA096082F");

                    b.HasIndex("metodo_de_pago_Id_metodo");

                    b.HasIndex("recibo_pago_Persona");

                    b.ToTable("recibo_pago_has_metodo");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("float");

                    b.Property<int>("reciboPago")
                        .HasColumnType("int");

                    b.Property<double?>("valorUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__recibo_p__3214EC071095D27E");

                    b.HasIndex("Producto");

                    b.HasIndex("reciboPago");

                    b.ToTable("recibo_productos");
                });

            modelBuilder.Entity("REMIwebApi.Models.role", b =>
                {
                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Desc_rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_Rol")
                        .HasName("PK__roles__55932E861BDE0F82");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("REMIwebApi.Models.stock", b =>
                {
                    b.Property<int>("Id_stock")
                        .HasColumnType("int");

                    b.Property<int?>("cantidadActual")
                        .HasColumnType("int");

                    b.Property<byte?>("estadoProducto")
                        .HasColumnType("tinyint");

                    b.Property<string>("productoStock")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("stockMax")
                        .HasColumnType("int");

                    b.Property<int?>("stockMin")
                        .HasColumnType("int");

                    b.HasKey("Id_stock")
                        .HasName("PK__stock__89C929197FF27049");

                    b.HasIndex("productoStock");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("REMIwebApi.Models.subcategoria", b =>
                {
                    b.Property<string>("Id_subcategoria")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("nombreSub")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id_subcategoria")
                        .HasName("PK__subcateg__5C3FC4A02D40F64A");

                    b.HasIndex("Categoria");

                    b.ToTable("subcategorias");
                });

            modelBuilder.Entity("REMIwebApi.Models.tipo_documento", b =>
                {
                    b.Property<string>("Id_tdoc")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Desc_tdoc")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.HasKey("Id_tdoc")
                        .HasName("PK__tipo_doc__717EF98083B9F9C0");

                    b.ToTable("tipo_documento");
                });

            modelBuilder.Entity("persona_has_role", b =>
                {
                    b.Property<int>("persona_Id_Persona")
                        .HasColumnType("int");

                    b.Property<int>("roles_Id_Rol")
                        .HasColumnType("int");

                    b.HasKey("persona_Id_Persona", "roles_Id_Rol")
                        .HasName("PK__persona___44FBF1518E916752");

                    b.HasIndex("roles_Id_Rol");

                    b.ToTable("persona_has_roles", (string)null);
                });

            modelBuilder.Entity("REMIwebApi.Models.movimientos_stock", b =>
                {
                    b.HasOne("REMIwebApi.Models.stock", "StockNavigation")
                        .WithMany("movimientos_stocks")
                        .HasForeignKey("Stock")
                        .IsRequired()
                        .HasConstraintName("FK__movimient__Stock__4F7CD00D");

                    b.Navigation("StockNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.persona", b =>
                {
                    b.HasOne("REMIwebApi.Models.tipo_documento", "tipoDocNavigation")
                        .WithMany("personas")
                        .HasForeignKey("tipoDoc")
                        .IsRequired()
                        .HasConstraintName("FK__persona__tipoDoc__3B75D760");

                    b.Navigation("tipoDocNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.producto", b =>
                {
                    b.HasOne("REMIwebApi.Models.proveedore", "ProveedorNavigation")
                        .WithMany("productos")
                        .HasForeignKey("Proveedor")
                        .IsRequired()
                        .HasConstraintName("FK__productos__Prove__49C3F6B7");

                    b.HasOne("REMIwebApi.Models.subcategoria", "SubcategoriaNavigation")
                        .WithMany("productos")
                        .HasForeignKey("Subcategoria")
                        .IsRequired()
                        .HasConstraintName("FK__productos__Subca__48CFD27E");

                    b.Navigation("ProveedorNavigation");

                    b.Navigation("SubcategoriaNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_pago", b =>
                {
                    b.HasOne("REMIwebApi.Models.cliente", "Id_clienteNavigation")
                        .WithMany("recibo_pagos")
                        .HasForeignKey("Id_cliente")
                        .HasConstraintName("FK__recibo_pa__Id_cl__5535A963");

                    b.HasOne("REMIwebApi.Models.persona", "PersonaNavigation")
                        .WithMany("recibo_pagos")
                        .HasForeignKey("Persona")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pa__Perso__5441852A");

                    b.Navigation("Id_clienteNavigation");

                    b.Navigation("PersonaNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_pago_has_metodo", b =>
                {
                    b.HasOne("REMIwebApi.Models.metodo_de_pago", "metodo_de_pago_Id_metodoNavigation")
                        .WithMany("recibo_pago_has_metodos")
                        .HasForeignKey("metodo_de_pago_Id_metodo")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pa__metod__5FB337D6");

                    b.HasOne("REMIwebApi.Models.recibo_pago", "recibo_pago_Id_reciboNavigation")
                        .WithMany("recibo_pago_has_metodos")
                        .HasForeignKey("recibo_pago_Id_recibo")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pa__recib__5DCAEF64");

                    b.HasOne("REMIwebApi.Models.persona", "recibo_pago_PersonaNavigation")
                        .WithMany("recibo_pago_has_metodos")
                        .HasForeignKey("recibo_pago_Persona")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pa__recib__5EBF139D");

                    b.Navigation("metodo_de_pago_Id_metodoNavigation");

                    b.Navigation("recibo_pago_Id_reciboNavigation");

                    b.Navigation("recibo_pago_PersonaNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_producto", b =>
                {
                    b.HasOne("REMIwebApi.Models.producto", "ProductoNavigation")
                        .WithMany("recibo_productos")
                        .HasForeignKey("Producto")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pr__Produ__59063A47");

                    b.HasOne("REMIwebApi.Models.recibo_pago", "reciboPagoNavigation")
                        .WithMany("recibo_productos")
                        .HasForeignKey("reciboPago")
                        .IsRequired()
                        .HasConstraintName("FK__recibo_pr__recib__5812160E");

                    b.Navigation("ProductoNavigation");

                    b.Navigation("reciboPagoNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.stock", b =>
                {
                    b.HasOne("REMIwebApi.Models.producto", "productoStockNavigation")
                        .WithMany("stocks")
                        .HasForeignKey("productoStock")
                        .IsRequired()
                        .HasConstraintName("FK__stock__productoS__4CA06362");

                    b.Navigation("productoStockNavigation");
                });

            modelBuilder.Entity("REMIwebApi.Models.subcategoria", b =>
                {
                    b.HasOne("REMIwebApi.Models.categoria", "CategoriaNavigation")
                        .WithMany("subcategoria")
                        .HasForeignKey("Categoria")
                        .IsRequired()
                        .HasConstraintName("FK__subcatego__Categ__45F365D3");

                    b.Navigation("CategoriaNavigation");
                });

            modelBuilder.Entity("persona_has_role", b =>
                {
                    b.HasOne("REMIwebApi.Models.persona", null)
                        .WithMany()
                        .HasForeignKey("persona_Id_Persona")
                        .IsRequired()
                        .HasConstraintName("FK__persona_h__perso__3E52440B");

                    b.HasOne("REMIwebApi.Models.role", null)
                        .WithMany()
                        .HasForeignKey("roles_Id_Rol")
                        .IsRequired()
                        .HasConstraintName("FK__persona_h__roles__3F466844");
                });

            modelBuilder.Entity("REMIwebApi.Models.categoria", b =>
                {
                    b.Navigation("subcategoria");
                });

            modelBuilder.Entity("REMIwebApi.Models.cliente", b =>
                {
                    b.Navigation("recibo_pagos");
                });

            modelBuilder.Entity("REMIwebApi.Models.metodo_de_pago", b =>
                {
                    b.Navigation("recibo_pago_has_metodos");
                });

            modelBuilder.Entity("REMIwebApi.Models.persona", b =>
                {
                    b.Navigation("recibo_pago_has_metodos");

                    b.Navigation("recibo_pagos");
                });

            modelBuilder.Entity("REMIwebApi.Models.producto", b =>
                {
                    b.Navigation("recibo_productos");

                    b.Navigation("stocks");
                });

            modelBuilder.Entity("REMIwebApi.Models.proveedore", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("REMIwebApi.Models.recibo_pago", b =>
                {
                    b.Navigation("recibo_pago_has_metodos");

                    b.Navigation("recibo_productos");
                });

            modelBuilder.Entity("REMIwebApi.Models.stock", b =>
                {
                    b.Navigation("movimientos_stocks");
                });

            modelBuilder.Entity("REMIwebApi.Models.subcategoria", b =>
                {
                    b.Navigation("productos");
                });

            modelBuilder.Entity("REMIwebApi.Models.tipo_documento", b =>
                {
                    b.Navigation("personas");
                });
#pragma warning restore 612, 618
        }
    }
}
